name: OnPushNewVersion


on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      # - name: Download CHANGELOG.md from release 
      #   uses: dsaltares/fetch-gh-release-asset@master
      #   with:    
      #     file: CHANGELOG.md
      #     target: CHANGELOG.md

      - name: Download artifacts (from StCore build action - MisbCoreNativeLib.dll, MisbCoreNativeLib.so, stored on ftp) 
        run: |
           wget --ftp-user=${{ secrets.FTP_USER }} --ftp-password=${{ secrets.FTP_PASSWORD }} ftp://ftp.impleotv.com//misbcoresdk/Native/Windows-x64/*
           wget --ftp-user=${{ secrets.FTP_USER }} --ftp-password=${{ secrets.FTP_PASSWORD }} ftp://ftp.impleotv.com//misbcoresdk/Native/Linux-x64/*
           wget --ftp-user=${{ secrets.FTP_USER }} --ftp-password=${{ secrets.FTP_PASSWORD }} ftp://ftp.impleotv.com//misbcoresdk/Native/Doc/CHANGELOG.md -O CHANGELOG.md

      - name: Zip file for windows-x64
        uses: papeloto/action-zip@v1
        with:
          files: MisbCoreNativeLib.dll
          dest:  /dist/MisbCoreNativeLib-windows-x64.zip

      - name: Zip file for linux-x64
        uses: papeloto/action-zip@v1
        with:
          files: MisbCoreNativeLib.so
          dest:  /dist/MisbCoreNativeLib-linux-x64.zip

      - name: List files in the repository
        run: |
          tree ${{ github.workspace }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.zip
          asset_name: MisbCoreNative
          tag: ${{ github.ref }}
          overwrite: true
          body: "MisbCoreNative release"
          file_glob: true

      - name: Setup NodeJs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}       
      - name: Generate README file
        run: node index.js ${{ env.RELEASE_VERSION }}
      - name: Commit and Push new README.md and CHANGELOG to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
